### ISSUE TITLE
What is the meaning and format of sGtk/ColorScheme in desktop.conf?

### ISSUE THREAD

**Issue by E3V3A** [raspberrypi-ui/LXDE-configuration#3]
In [desktop.conf](https://github.com/raspberrypi-ui/LXDE-configuration/blob/master/config/lxsession/LXDE-pi/desktop.conf), there is the line:
```
sGtk/ColorScheme=selected_bg_color:#4d4d9898f5f5\nselected_fg_color:#ffffffffffff\nbar_bg_color:#ededececebeb\nbar_fg_color:#000000000000\n
```
**How can I understand what the 12 hex digits mean? **  
Usually there are only 6 (3 bytes).

**Comment by spl237** [comment]
Each R, G and B value is a 32 bit number, so 4 octets each.

BTW, this isn't a bug - it's a question. In future, the Raspberry Pi forums are the place for things like this rather than Github.

**Comment by JamesH65** [comment]
Although one would have to say that this is actually a GTK question, not specific to Raspberry Pi, and therefore either the GTK mailing lists, or even a Google search would be the best approach.
