### ISSUE TITLE
Conflict between Taskbar settings and Desktop settings 

### ISSUE THREAD

**Issue by rin67630** [raspberrypi-ui/LXDE-configuration#4]
Please let me file a bug that exists for at least 3 years in every Raspbian version.
I use to use my taskbar leftsided with 70pixel width.
Each time I make a change in the desktop preferences even unrelated to the taskbar, my taskbar settings gets overwritten and the taskbar is on top again, 
Can that be corrected?
Thank you.

**Comment by spl237** [comment]
No, I'm sorry, this cannot be changed. The Desktop Preferences app shows a radio button with only two options for taskbar position, and it will therefore set the taskbar to either top or bottom; no other options are supported by the application. This is by design, as using the taskbar at the side of the screen is inefficient in terms of space used; if you prefer it, that's fine, but it will not be a configuration we support.

**Comment by rin67630** [comment]
I love the autocratic justification: "This is by design, as using the taskbar at the side of the screen is inefficient in terms of space used"
Who defines inefficient? Is Ubuntu's design inefficient?
Just at the opposite: the left taskbar is today, with 16:9 desktops, more efficient than ever! 
With portrait documents and a paramount style monitor with application menus and ribbons stealing the vertical real estate, having the taskbar on the side is a refreshing experience.

**Comment by rin67630** [comment]
P.S. Why must the Desktop Preferences handle the taskbar settings? The taskbar has its own preferences. The conflict still exists.

**Comment by pelwell** [comment]
Just a hint - don't expect to change @spl237's mind. We've tried and failed often enough, and I wouldn't want you to think you have a chance. But if you just want to rail against the injustice of it all, be my guest.

**Comment by rin67630** [comment]
No it's not injustice. He does his job for us for free. He is the boss and we are grateful to get FOSS. 
But maybe the idea of removing the taskbar settings from the desktop would also make his job easier?

**Comment by rin67630** [comment]
Please note: the "Appearance Settings" are still called "Desktop Preferences" if you right click on the desktop.
Anyhow and beside all personal preferences, just letting the Panel Settings on the Panel and the Desktop Settings* on the Desktop does not seem to be without sense, isn't it?

*Appearance Settings or Desktop Settings, how ever you call it.

**Comment by spl237** [comment]
The menu item reads "desktop settings" - the application window is titled "Appearance Settings", and it opens on a tab titled "Desktop". It doesn't seem to have caused much confusion...

Splitting panel and desktop settings into separate applications would undo the whole purpose of having a single appearance settings application - for example, it then becomes necessary to set the font in three separate places for desktop, taskbar and applications; this is precisely the issue that the Appearance Settings app was created to address.

You are free to install and use the separate original LXDE apps for appearance for openbox, desktop, GTK and the taskbar; they are all either still installed or still in apt, and the application launched by the desktop settings menu item can be customised in the config file for PCManFM and reset to that provided by the desktop itself.
