### ISSUE TITLE
The defaults settings in appearance settings are overwritten by system update.

### ISSUE THREAD

**Issue by rin67630** [raspberrypi-ui/LXDE-configuration#5]
The defaults settings in appearance settings e.g "small screen" are are overwritten by a system update without notice. Can that be corrected?

**Comment by spl237** [comment]
No, this is unfortunately unavoidable; LXDE doesn't offer a useful mechanism for upgrading settings files. Your old settings files are backed up in the "oldconfig" directory in your home directory, so you can restored them from there if desired.
